const ActionTYpes = {
    SET_PRODUCTS:"SET_PRODUCTS",
    SELECT_PRODUCT:"SELECT_PRODUCT",
    REMOVE_SELECTED_PRODUCT:"REMOVE_SELECTED_PRODUCT",
    FETCH_DATA:"FETCH_DATA"
}

export default ActionTYpes